import Link from "next/link";
import Image from "next/image";
import { Sparkles,Camera,ScanLine,Copy,ShieldCheck,Clock3,Layers,Check,Plus } from "lucide-react";
import { Navbar } from "@/components/navbar";
import { Brand } from "@/components/brand";
import { siteConfig } from "@/lib/config";
export default function Home(){return <><Navbar/><main id="main-content"><section className="hero container"><div className="hero-copy"><div className="pill"><Sparkles size={15}/> La seconde main, avec une longueur d’avance</div><h1>Une photo.<br/>Une belle annonce.<br/><span>C’est vendu.</span></h1><p className="hero-subtitle">Transforme tes photos en annonces Vinted qui donnent envie d’acheter.</p><p className="hero-description">Importe une photo. L’IA crée ton titre, ta description et transforme ta photo en visuel professionnel.</p><div className="hero-ctas"><Link className="button primary large" href="/dashboard/listing-generator"><Sparkles size={19}/>Générer mon annonce</Link><Link className="button secondary large" href="/dashboard/photo-studio"><Camera size={19}/>Découvrir le studio photo</Link></div><div className="hero-assurances"><span><Check size={15}/> Simple à utiliser</span><span><Check size={15}/> Sans carte bancaire</span></div></div><div className="hero-demo"><div className="demo-topline"><span className="small-caps">LE STUDIO SELLAI</span><span className="demo-symbol">✳</span></div><div className="demo-photo"><Image src="/demo-v2.webp" alt="Exemple illustratif : le même sweat vert sur un parquet puis sur un tapis gris clair" width={1330} height={1182} priority sizes="(max-width: 900px) 90vw, 45vw"/><div className="demo-photo-labels"><span>Ta photo</span><span><Sparkles size={14}/>Avec SellAI</span></div></div><div className="demo-listing"><div className="demo-listing-icon"><ScanLine size={20}/></div><div><span className="small-caps">EXEMPLE D’ANNONCE</span><strong>Sweat vert à coupe ample</strong><p>Un style décontracté, une couleur qui fait la différence.</p></div><span className="demo-check"><Check size={18}/></span></div><div className="demo-caption">Visuels et annonce d’illustration. Les résultats réels dépendent de ta photo.</div></div></section>
 <section className="workflow-band"><div className="container"><span>Moins de temps à rédiger.<br/><strong>Plus de place pour vendre.</strong></span><div className="workflow-step"><span>01</span> Importe ta photo</div><Plus className="workflow-plus" size={20}/><div className="workflow-step"><span>02</span> Laisse l’IA travailler</div><Plus className="workflow-plus" size={20}/><div className="workflow-step"><span>03</span> Copie et publie</div></div></section>
 <section className="features container" id="features"><div className="section-heading"><span className="eyebrow">TON PETIT COUP DE POUCE POUR VENDRE</span><h2>Tout ce qu’il faut.<br/>Rien de compliqué.</h2><p>Ton article a déjà une histoire. Donne-lui une présentation à sa hauteur.</p></div><div className="feature-grid"><article className="feature-card feature-main"><div className="feature-icon"><SquarePenIcon/></div><h3>Les bons mots,<br/>sans la page blanche.</h3><p>Un titre précis, une description naturelle et les caractéristiques visibles. Tu gardes la main sur chaque mot.</p><div className="feature-snippet"><span>✨ Sweat vert à coupe ample</span><div/><div/><span className="snippet-tag"><Copy size={13}/> Prêt à copier</span></div></article><article className="feature-card"><div className="feature-icon"><Camera/></div><h3>Ton studio photo,<br/>en un clic.</h3><p>Un tapis gris clair, une lumière neutre et une présentation cohérente pour tous tes articles.</p><Link href="/dashboard/photo-studio" className="text-link">Ouvrir le studio</Link></article><article className="feature-card"><div className="feature-icon"><Layers/></div><h3>Ta créativité<br/>reste avec toi.</h3><p>Retrouve tes annonces et tes photos, modifie-les et télécharge-les depuis ton espace personnel.</p><Link href="/dashboard/history" className="text-link">Voir mes créations</Link></article></div><div className="benefit-row"><span><Clock3 size={20}/> Moins de tâches répétitives</span><span><ShieldCheck size={20}/> Un espace privé</span><span><ScanLine size={20}/> Seulement les détails identifiables</span></div></section>
 <section className="bottom-cta container"><div><span className="eyebrow">PRÊT POUR UNE SECONDE VIE ?</span><h2>Ton prochain acheteur<br/>n’attend qu’une belle annonce.</h2></div><Link href="/register" className="button primary large">Essayer gratuitement</Link><span className="cta-star">✳</span></section></main><footer className="footer container"><Brand/><p>{siteConfig.name} est un assistant indépendant, sans affiliation avec Vinted.</p><Link href="/demo">Voir l’exemple</Link></footer></>;}
function SquarePenIcon(){return <ScanLine/>;}

