"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { Trash2,Download,Plus,LoaderCircle } from "lucide-react";
import { toast } from "sonner";
import { api,message,downloadImage } from "@/lib/client";
import type { Listing,GeneratedImage } from "@/lib/schemas";
import { ConfirmDialog,EmptyState,LoadingState } from "./ui";
export function History(){
 const [tab,setTab]=useState<"listings"|"images">("listings"),[listings,setListings]=useState<Listing[]>([]),[images,setImages]=useState<GeneratedImage[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(""),[deleting,setDeleting]=useState(""),[downloading,setDownloading]=useState(""),[more,setMore]=useState(false),[loadingMore,setLoadingMore]=useState(false);
 async function load(append=false){if(append)setLoadingMore(true);else{setBusy(true);setError("");}try{const offset=append?(tab==="listings"?listings.length:images.length):0;const data=await api<Array<Listing&GeneratedImage>>(`/api/${tab}?offset=${offset}`);if(tab==="listings")setListings(old=>append?[...old,...data]:data);else setImages(old=>append?[...old,...data]:data);setMore(data.length===24);}catch(e){setError(message(e));}finally{setBusy(false);setLoadingMore(false);}}
 useEffect(()=>{void load();},[tab]);
 async function remove(id:string){setDeleting(id);try{await api(`/api/${tab}/${id}`,{method:"DELETE"});if(tab==="listings")setListings(rows=>rows.filter(row=>row.id!==id));else setImages(rows=>rows.filter(row=>row.id!==id));toast.success("Création supprimée.");}catch(e){toast.error(message(e));}finally{setDeleting("");}}
 async function download(id:string){setDownloading(id);try{await downloadImage(id);toast.success("Image téléchargée.");}catch(e){toast.error(message(e));}finally{setDownloading("");}}
 const date=(value:string)=>new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value));
 const rows=tab==="listings"?listings:images;
 return <><div className="history-tabs" role="group" aria-label="Type de créations"><button className={tab==="listings"?"active":""} aria-pressed={tab==="listings"} onClick={()=>{if(!busy)setTab("listings");}}>Annonces</button><button className={tab==="images"?"active":""} aria-pressed={tab==="images"} onClick={()=>{if(!busy)setTab("images");}}>Photos</button></div>{busy?<section className="panel"><LoadingState/></section>:error?<section className="panel history-error"><p role="alert">{error}</p><button className="button secondary" onClick={()=>void load()}>Réessayer</button></section>:!rows.length?<section className="panel"><EmptyState title={tab==="listings"?"Ta première annonce t’attend.":"Le studio attend ton premier article."} description="Tes créations sont enregistrées ici, uniquement pour toi."><Link className="button primary" href={tab==="listings"?"/dashboard/listing-generator":"/dashboard/photo-studio"}><Plus size={18}/>Créer maintenant</Link></EmptyState></section>:<><div className="history-grid">{tab==="listings"?listings.map(row=><article className="history-card" key={row.id}><Link href={`/dashboard/listing-generator?id=${row.id}`}><img className="history-thumbnail" src={row.media.url} alt={row.title} loading="lazy"/></Link><div className="history-body"><h3>{row.title}</h3><time dateTime={row.created_at}>{date(row.created_at)}</time><div className="history-actions"><Link className="button secondary small" href={`/dashboard/listing-generator?id=${row.id}`}>Ouvrir</Link><ConfirmDialog busy={deleting===row.id} onConfirm={()=>remove(row.id)}><button className="icon-button" aria-label={`Supprimer ${row.title}`}><Trash2 size={17}/></button></ConfirmDialog></div></div></article>):images.map(row=><article className="history-card" key={row.id}><Link className="history-pair" href={`/dashboard/photo-studio?id=${row.id}`}><img src={row.source.url} alt="Original" loading="lazy"/><img src={row.result.url} alt="Résultat IA" loading="lazy"/></Link><div className="history-body"><h3>Photo studio · 9:16</h3><time dateTime={row.created_at}>{date(row.created_at)}</time><div className="history-actions"><Link className="button secondary small" href={`/dashboard/photo-studio?id=${row.id}`}>Ouvrir</Link><button className="icon-button" aria-label="Télécharger la photo" disabled={downloading===row.result.id} onClick={()=>download(row.result.id)}>{downloading===row.result.id?<LoaderCircle className="spin" size={17}/>:<Download size={17}/>}</button><ConfirmDialog busy={deleting===row.id} onConfirm={()=>remove(row.id)}><button className="icon-button" aria-label="Supprimer cette photo"><Trash2 size={17}/></button></ConfirmDialog></div></div></article>)}</div>{more?<button style={{marginTop:25}} className="button secondary" disabled={loadingMore} onClick={()=>void load(true)}>{loadingMore?"Chargement...":"Charger plus"}</button>:null}</> }</>;
}
