import Link from "next/link";
import { SquarePen,Camera,Layers,ImagePlus } from "lucide-react";
import { requireUser,adminClient } from "@/lib/auth/server";
import { profileFor,listingsFor,imagesFor } from "@/lib/database/server";
import { dbCheck } from "@/lib/server/errors";
import { EmptyState } from "@/components/ui";
export default async function Dashboard(){
 const {user}=await requireUser();
 const [profile,listings,images,listingCount,imageCount]=await Promise.all([profileFor(user.id),listingsFor(user.id),imagesFor(user.id),adminClient().from("listings").select("id",{count:"exact",head:true}).eq("user_id",user.id),adminClient().from("generated_images").select("id",{count:"exact",head:true}).eq("user_id",user.id)]);
 dbCheck(listingCount.error);dbCheck(imageCount.error);
 const recent=[...listings.map(row=>({id:row.id,title:row.title,url:row.media.url,date:row.created_at,href:`/dashboard/listing-generator?id=${row.id}`})),...images.map(row=>({id:row.id,title:"Photo studio · 9:16",url:row.result.url,date:row.created_at,href:`/dashboard/photo-studio?id=${row.id}`}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);
 return <div id="main-content"><div className="page-heading"><span className="eyebrow">UNE BELLE JOURNÉE POUR DONNER UNE SECONDE VIE</span><h1>Bonjour {profile.first_name||"à toi"} <span style={{color:"#82a848"}}>✦</span></h1><p>Quel article va faire sa meilleure première impression aujourd’hui ?</p></div><div className="stats-grid"><section className="panel stat"><div><span>Annonces créées</span><strong>{listingCount.count||0}</strong></div><span className="stat-icon"><SquarePen/></span></section><section className="panel stat"><div><span>Photos générées</span><strong>{imageCount.count||0}</strong></div><span className="stat-icon"><Camera/></span></section><section className="panel stat"><div><span>{profile.credit_balance===null?"Ton espace":"Crédits disponibles"}</span><strong>{profile.credit_balance===null?"Personnel":profile.credit_balance}</strong></div><span className="stat-icon"><Layers/></span></section></div><div className="action-grid"><Link className="action-card" href="/dashboard/listing-generator"><SquarePen size={27}/><h2>Créer une annonce</h2><p>Ta photo devient un titre précis et une description prête à copier. Quelques clics, et c’est fait.</p><span className="button primary small">Générer mon annonce</span></Link><Link className="action-card" href="/dashboard/photo-studio"><ImagePlus size={27}/><h2>Retoucher une photo</h2><p>Une présentation cohérente pour tes produits, avec un fond gris clair et une lumière neutre.</p><span className="button secondary small">Ouvrir le studio</span></Link></div><div className="panel-title"><h2>Mes dernières créations</h2><Link className="text-link" href="/dashboard/history">Tout voir</Link></div>{recent.length?<div className="history-grid">{recent.map(row=><Link className="history-card" href={row.href} key={row.id}><img className="history-thumbnail" src={row.url} alt={row.title} loading="lazy"/><div className="history-body"><h3>{row.title}</h3><time dateTime={row.date}>{new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"long"}).format(new Date(row.date))}</time></div></Link>)}</div>:<section className="panel"><EmptyState title="Tout commence par une photo." description="Tes nouvelles annonces et photos apparaîtront ici."/></section>}</div>;
}
